### ISSUE TITLE
virtu always generate link with full scheme

### ISSUE THREAD

**Issue by kudykam** [virtudraft/virtuNewsletter#21]
For unsubscription link in email it is recommended to add  &scheme=`full` (RTFM)
but link is always generate in full URL no matter what setting I use..

-1 : (default value) URL is relative to site_url
0 : see http
1 : see https
full : URL is absolute, prepended with site_url from config
abs : URL is absolute, prepended with base_url from config
http : URL is absolute, forced to http scheme
https : URL is absolute, forced to https scheme

**Comment by goldsky** [comment]
It is in the core, because the link would not be the email's domain, would it?
