### ISSUE TITLE
Queue not processing?

### ISSUE THREAD

**Issue by matdave** [virtudraft/virtuNewsletter#30]
I set up an email schedule with 400 subscribers.  I set it to send 5 p/ Week.  I have the cron process running, and the first two scheduled times have came and went.  It still says "queued" for each of the emails, and has now queued emails for both sets. 

Mandrill is showing only 3 emails sent (which were from another schedule with just me on it), so they are definitely not being processed.  I tried hitting "Send All", but it doesn't do anything.

**Comment by goldsky** [comment]
closing this issue.
open new one if the problem persists.
