### ISSUE TITLE
Blank CMP MODX Revolution 2.3.3-pl

### ISSUE THREAD

**Issue by vacatoro** [virtudraft/virtuNewsletter#39]
I have just installed virtuNewsletter via the Installer but get a completely blank page when I try to access the CMP. I tried to remove the core/cache manually, cleared browser cache, uninstalled and reinstalled without luck. I assume it is a namespace or controller problem and I tried to investigate by comparing to Lingua (which runs without problems) but I don't know enough to spot it. 

Any ideas? Many thanks!

MODX Revolution 2.3.3-pl
PHP Version 5.2.11

**Comment by goldsky** [comment]
I'll check about it.

**Comment by goldsky** [comment]
Different action on new MODX.
Updated on https://github.com/virtudraft/virtuNewsletter/commit/179df484370933662d4d0f44d9277a470abab68b#diff-46bed95a2c5bce33ba457591894681c8R135
