### ISSUE TITLE
'Scheduled for' option doesn't matter?

### ISSUE THREAD

**Issue by glukash** [virtudraft/virtuNewsletter#40]
Does 'Scheduled for' matter anything?
Once the new schedule is set it doesn't check for the 'Scheduled for' option.
Either it is the past date or the future date emails are being sent immediately after new schedule is set.

**Comment by goldsky** [comment]
new schema is now no longer required
https://github.com/virtudraft/virtuNewsletter/blob/develop/core/components/virtunewsletter/model/schema/virtunewsletter.mysql.schema.xml#L35
