### ISSUE TITLE
Multilingual Newsletter with Babel

### ISSUE THREAD

**Issue by navtsi** [virtudraft/virtuNewsletter#41]
How can I change the unsubscribe and read online links for newsletters in different languages. I'm using Balbe for creating one context for each language. In this case the unsubscribe and read online link has to contain the cultureKey, but they would created without the key.

**Comment by goldsky** [comment]
If you distinct the contexts by subdomain, you don't need it.
Otherwise, just add ``` &cultureKey=`the_context_key` ``` like this:
Example from [rtfm](https://rtfm.modx.com/extras/revo/virtunewsletter#virtuNewsletter-5.TheNewsletters)
```
<!-- unsubscribe link -->
<a href="[[~62? 
&subid=`[[+virtuNewsletter.email.subid]]` 
&h=`[[+virtuNewsletter.email.hash]]`
&act=`unsubscribe`
&scheme=`full`
&cultureKey=`de`
]]">
Unsubscribe
</a>
<!-- read the newsletter on the website -->
<a href="[[~63?
&scheme=`full`
&newsid=`[[+virtuNewsletter.email.newsid]]`
&e=`[[+virtuNewsletter.email.email]]`
&h=`[[+virtuNewsletter.email.hash]]`
&cultureKey=`de`
]]">read this newsletter on the website</a>
```
